{% set name = "traviscli" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/traviscli-{{ version }}.tar.gz
  sha256: c2236da8bdba857b7db3375c00512694dfb5e71f83c659ec78f7d9c3add09b6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - traviscli=travisci.TravisCli:commandHandler

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - python >=3.6
    - pytravisci

test:
  imports:
    - travisci
    - travisci.exceptions
  commands:
    - pip check
    - traviscli --help
  requires:
    - pip

about:
  home: https://github.com/hasii2011/travisci-cli
  summary: A build help tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
